re-configure db migration.

diff --git a/apps/my-sample-app-1/migration-bundle/Dockerfile b/apps/my-sample-app-1/migration-bundle/Dockerfile
--- a/apps/my-sample-app-1/migration-bundle/Dockerfile
+++ b/apps/my-sample-app-1/migration-bundle/Dockerfile
@@ -34,12 +34,22 @@ COPY --from=build /app/migrations-bundle .
 # Grant execute permissions if necessary (for Linux)
 RUN chmod +x ./migrations-bundle
 
-#Create a shell script to log the connection string and run the bundle
-RUN echo '#!/bin/sh' > /app/run-migrations.sh && \
-    echo 'CONNECTION_STRING="Host=$DB__POSTGRES_HOST;Port=$DB__POSTGRES_PORT;Database=$DB__POSTGRES_DB;Username=$DB__POSTGRES_USER;Password=$DB__POSTGRES_PASSWORD"' >> /app/run-migrations.sh && \
-    echo 'echo "Using connection string: $CONNECTION_STRING"' >> /app/run-migrations.sh && \
-    echo './migrations-bundle --connection "$CONNECTION_STRING" --verbose' >> /app/run-migrations.sh && \
-    chmod +x /app/run-migrations.sh
-
-# Set the entrypoint to the shell script
-ENTRYPOINT [ "/app/run-migrations.sh" ]
+# Set the entrypoint to handle different scenarios based on arguments
+ENTRYPOINT ["/bin/sh", "-c", \
+    'CONNECTION_STRING="Host=$DB__POSTGRES_HOST;Port=$DB__POSTGRES_PORT;Database=$DB__POSTGRES_DB;Username=$DB__POSTGRES_USER;Password=$DB__POSTGRES_PASSWORD"; \
+    if [ "$ASPNETCORE_ENVIRONMENT" = "Development" ]; then \
+    echo "Using connection string: $CONNECTION_STRING"; \
+    fi; \
+    if [ -z "$1" ]; then \
+    echo "Error: No arguments provided. Exiting with error."; \
+    exit 1; \
+    elif [ "$1" = "apply" ]; then \
+    echo "Applying all migrations..."; \
+    ./migrations-bundle --connection "$CONNECTION_STRING"; \
+    elif [ "$1" = "reset" ]; then \
+    echo "Resetting database to initial state (no migrations)..."; \
+    ./migrations-bundle --connection "$CONNECTION_STRING" --target 0; \
+    else \
+    echo "Rolling back to migration: $1"; \
+    ./migrations-bundle --connection "$CONNECTION_STRING" --target "$1"; \
+    fi']
